apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service

spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service

    # 파드에 세팅되는 컨테이너 설정
    spec:
      imagePullSecrets: # 우리의 image 저장소가 private하기 때문에 계정 정보를 Secret 오브젝트로 세팅.
        - name: ecr-secret # 우리가 직접 만든 SECRET 오브젝트. 여기에 Ecr 접근 권한 계정 접ㅇ보 들어있다.
      containers:
        - name: config-service
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}